site_name: kosmos-craftroom
site_url: https://zkbt.github.com/kosmos-craftroom
nav:
    - Welcome: index.md
    - installation.ipynb
    - catalogs.ipynb
    - finders.ipynb
    - scripting.ipynb
    - log.ipynb
    - signal-to-noise.ipynb
    - quicklook.ipynb

theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/kosmos-craftroom/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
      include: ["*.py", "*.ipynb", ".mp4"]
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../kosmoscraftroom]
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: True
            show_root_heading: True
            show_root_toc_entry: False
            show_root_full_path: False
            show_category_heading: False
            show_submodules: False
            merge_init_into_class: False
            show_if_no_docstring: False
            heading_level: 3
            show_bases: False
  - exclude:
      glob:
        - "*.pdf"
        - "*.fits"
        - "*.npy"
        - "exoatlas-downloads"
markdown_extensions:
    - toc:
        permalink: "#"

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
